quarkus:
  http:
    port: 8082
    root-path: /api/

  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://db:5432/product_db

  rest-client:
    "com.dev.client.CustomerClient":
      url: http://localhost:8080/api
    "com.dev.client.ProductClient":
      url: http://localhost:8081/api

  hibernate-orm:
    database:
      generation: update